# Generated by Django 4.1.4 on 2022-12-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BookSearch',
        ),
    ]
